// HW2.v

// Generated using ACDS version 24.1 1077

`timescale 1 ps / 1 ps
module HW2 (
		input  wire       clk_clk,         //      clk.clk
		input  wire [3:0] keys_export,     //     keys.export
		output wire [9:0] leds_export,     //     leds.export
		input  wire [9:0] switches_export  // switches.export
	);

	wire         hw2_dbg_reset_out_reset;                               // HW2:dbg_reset_out_reset -> [HW2:ndm_reset_in_reset, rst_controller:reset_in0]
	wire  [31:0] hw2_data_manager_awaddr;                               // HW2:data_manager_awaddr -> mm_interconnect_0:HW2_data_manager_awaddr
	wire   [1:0] hw2_data_manager_bresp;                                // mm_interconnect_0:HW2_data_manager_bresp -> HW2:data_manager_bresp
	wire         hw2_data_manager_arready;                              // mm_interconnect_0:HW2_data_manager_arready -> HW2:data_manager_arready
	wire  [31:0] hw2_data_manager_rdata;                                // mm_interconnect_0:HW2_data_manager_rdata -> HW2:data_manager_rdata
	wire   [3:0] hw2_data_manager_wstrb;                                // HW2:data_manager_wstrb -> mm_interconnect_0:HW2_data_manager_wstrb
	wire         hw2_data_manager_wready;                               // mm_interconnect_0:HW2_data_manager_wready -> HW2:data_manager_wready
	wire         hw2_data_manager_awready;                              // mm_interconnect_0:HW2_data_manager_awready -> HW2:data_manager_awready
	wire         hw2_data_manager_rready;                               // HW2:data_manager_rready -> mm_interconnect_0:HW2_data_manager_rready
	wire         hw2_data_manager_bready;                               // HW2:data_manager_bready -> mm_interconnect_0:HW2_data_manager_bready
	wire         hw2_data_manager_wvalid;                               // HW2:data_manager_wvalid -> mm_interconnect_0:HW2_data_manager_wvalid
	wire  [31:0] hw2_data_manager_araddr;                               // HW2:data_manager_araddr -> mm_interconnect_0:HW2_data_manager_araddr
	wire   [2:0] hw2_data_manager_arprot;                               // HW2:data_manager_arprot -> mm_interconnect_0:HW2_data_manager_arprot
	wire   [1:0] hw2_data_manager_rresp;                                // mm_interconnect_0:HW2_data_manager_rresp -> HW2:data_manager_rresp
	wire   [2:0] hw2_data_manager_awprot;                               // HW2:data_manager_awprot -> mm_interconnect_0:HW2_data_manager_awprot
	wire  [31:0] hw2_data_manager_wdata;                                // HW2:data_manager_wdata -> mm_interconnect_0:HW2_data_manager_wdata
	wire         hw2_data_manager_arvalid;                              // HW2:data_manager_arvalid -> mm_interconnect_0:HW2_data_manager_arvalid
	wire         hw2_data_manager_bvalid;                               // mm_interconnect_0:HW2_data_manager_bvalid -> HW2:data_manager_bvalid
	wire         hw2_data_manager_awvalid;                              // HW2:data_manager_awvalid -> mm_interconnect_0:HW2_data_manager_awvalid
	wire         hw2_data_manager_rvalid;                               // mm_interconnect_0:HW2_data_manager_rvalid -> HW2:data_manager_rvalid
	wire  [31:0] hw2_instruction_manager_awaddr;                        // HW2:instruction_manager_awaddr -> mm_interconnect_0:HW2_instruction_manager_awaddr
	wire   [1:0] hw2_instruction_manager_bresp;                         // mm_interconnect_0:HW2_instruction_manager_bresp -> HW2:instruction_manager_bresp
	wire         hw2_instruction_manager_arready;                       // mm_interconnect_0:HW2_instruction_manager_arready -> HW2:instruction_manager_arready
	wire  [31:0] hw2_instruction_manager_rdata;                         // mm_interconnect_0:HW2_instruction_manager_rdata -> HW2:instruction_manager_rdata
	wire   [3:0] hw2_instruction_manager_wstrb;                         // HW2:instruction_manager_wstrb -> mm_interconnect_0:HW2_instruction_manager_wstrb
	wire         hw2_instruction_manager_wready;                        // mm_interconnect_0:HW2_instruction_manager_wready -> HW2:instruction_manager_wready
	wire         hw2_instruction_manager_awready;                       // mm_interconnect_0:HW2_instruction_manager_awready -> HW2:instruction_manager_awready
	wire         hw2_instruction_manager_rready;                        // HW2:instruction_manager_rready -> mm_interconnect_0:HW2_instruction_manager_rready
	wire         hw2_instruction_manager_bready;                        // HW2:instruction_manager_bready -> mm_interconnect_0:HW2_instruction_manager_bready
	wire         hw2_instruction_manager_wvalid;                        // HW2:instruction_manager_wvalid -> mm_interconnect_0:HW2_instruction_manager_wvalid
	wire  [31:0] hw2_instruction_manager_araddr;                        // HW2:instruction_manager_araddr -> mm_interconnect_0:HW2_instruction_manager_araddr
	wire   [2:0] hw2_instruction_manager_arprot;                        // HW2:instruction_manager_arprot -> mm_interconnect_0:HW2_instruction_manager_arprot
	wire   [1:0] hw2_instruction_manager_rresp;                         // mm_interconnect_0:HW2_instruction_manager_rresp -> HW2:instruction_manager_rresp
	wire   [2:0] hw2_instruction_manager_awprot;                        // HW2:instruction_manager_awprot -> mm_interconnect_0:HW2_instruction_manager_awprot
	wire  [31:0] hw2_instruction_manager_wdata;                         // HW2:instruction_manager_wdata -> mm_interconnect_0:HW2_instruction_manager_wdata
	wire         hw2_instruction_manager_arvalid;                       // HW2:instruction_manager_arvalid -> mm_interconnect_0:HW2_instruction_manager_arvalid
	wire         hw2_instruction_manager_bvalid;                        // mm_interconnect_0:HW2_instruction_manager_bvalid -> HW2:instruction_manager_bvalid
	wire         hw2_instruction_manager_awvalid;                       // HW2:instruction_manager_awvalid -> mm_interconnect_0:HW2_instruction_manager_awvalid
	wire         hw2_instruction_manager_rvalid;                        // mm_interconnect_0:HW2_instruction_manager_rvalid -> HW2:instruction_manager_rvalid
	wire         mm_interconnect_0_debug_avalon_jtag_slave_chipselect;  // mm_interconnect_0:DEBUG_avalon_jtag_slave_chipselect -> DEBUG:av_chipselect
	wire  [31:0] mm_interconnect_0_debug_avalon_jtag_slave_readdata;    // DEBUG:av_readdata -> mm_interconnect_0:DEBUG_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_debug_avalon_jtag_slave_waitrequest; // DEBUG:av_waitrequest -> mm_interconnect_0:DEBUG_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_debug_avalon_jtag_slave_address;     // mm_interconnect_0:DEBUG_avalon_jtag_slave_address -> DEBUG:av_address
	wire         mm_interconnect_0_debug_avalon_jtag_slave_read;        // mm_interconnect_0:DEBUG_avalon_jtag_slave_read -> DEBUG:av_read_n
	wire         mm_interconnect_0_debug_avalon_jtag_slave_write;       // mm_interconnect_0:DEBUG_avalon_jtag_slave_write -> DEBUG:av_write_n
	wire  [31:0] mm_interconnect_0_debug_avalon_jtag_slave_writedata;   // mm_interconnect_0:DEBUG_avalon_jtag_slave_writedata -> DEBUG:av_writedata
	wire  [31:0] mm_interconnect_0_hw2_dm_agent_readdata;               // HW2:dm_agent_readdata -> mm_interconnect_0:HW2_dm_agent_readdata
	wire         mm_interconnect_0_hw2_dm_agent_waitrequest;            // HW2:dm_agent_waitrequest -> mm_interconnect_0:HW2_dm_agent_waitrequest
	wire  [15:0] mm_interconnect_0_hw2_dm_agent_address;                // mm_interconnect_0:HW2_dm_agent_address -> HW2:dm_agent_address
	wire         mm_interconnect_0_hw2_dm_agent_read;                   // mm_interconnect_0:HW2_dm_agent_read -> HW2:dm_agent_read
	wire         mm_interconnect_0_hw2_dm_agent_readdatavalid;          // HW2:dm_agent_readdatavalid -> mm_interconnect_0:HW2_dm_agent_readdatavalid
	wire         mm_interconnect_0_hw2_dm_agent_write;                  // mm_interconnect_0:HW2_dm_agent_write -> HW2:dm_agent_write
	wire  [31:0] mm_interconnect_0_hw2_dm_agent_writedata;              // mm_interconnect_0:HW2_dm_agent_writedata -> HW2:dm_agent_writedata
	wire         mm_interconnect_0_leds_s1_chipselect;                  // mm_interconnect_0:LEDS_s1_chipselect -> LEDS:chipselect
	wire  [31:0] mm_interconnect_0_leds_s1_readdata;                    // LEDS:readdata -> mm_interconnect_0:LEDS_s1_readdata
	wire   [1:0] mm_interconnect_0_leds_s1_address;                     // mm_interconnect_0:LEDS_s1_address -> LEDS:address
	wire         mm_interconnect_0_leds_s1_write;                       // mm_interconnect_0:LEDS_s1_write -> LEDS:write_n
	wire  [31:0] mm_interconnect_0_leds_s1_writedata;                   // mm_interconnect_0:LEDS_s1_writedata -> LEDS:writedata
	wire  [31:0] mm_interconnect_0_keys_s1_readdata;                    // KEYS:readdata -> mm_interconnect_0:KEYS_s1_readdata
	wire   [1:0] mm_interconnect_0_keys_s1_address;                     // mm_interconnect_0:KEYS_s1_address -> KEYS:address
	wire  [31:0] mm_interconnect_0_switches_s1_readdata;                // SWITCHES:readdata -> mm_interconnect_0:SWITCHES_s1_readdata
	wire   [1:0] mm_interconnect_0_switches_s1_address;                 // mm_interconnect_0:SWITCHES_s1_address -> SWITCHES:address
	wire         mm_interconnect_0_sdram_s1_chipselect;                 // mm_interconnect_0:SDRAM_s1_chipselect -> SDRAM:chipselect
	wire  [31:0] mm_interconnect_0_sdram_s1_readdata;                   // SDRAM:readdata -> mm_interconnect_0:SDRAM_s1_readdata
	wire  [15:0] mm_interconnect_0_sdram_s1_address;                    // mm_interconnect_0:SDRAM_s1_address -> SDRAM:address
	wire   [3:0] mm_interconnect_0_sdram_s1_byteenable;                 // mm_interconnect_0:SDRAM_s1_byteenable -> SDRAM:byteenable
	wire         mm_interconnect_0_sdram_s1_write;                      // mm_interconnect_0:SDRAM_s1_write -> SDRAM:write
	wire  [31:0] mm_interconnect_0_sdram_s1_writedata;                  // mm_interconnect_0:SDRAM_s1_writedata -> SDRAM:writedata
	wire         mm_interconnect_0_sdram_s1_clken;                      // mm_interconnect_0:SDRAM_s1_clken -> SDRAM:clken
	wire  [31:0] mm_interconnect_0_hw2_timer_sw_agent_readdata;         // HW2:timer_sw_agent_readdata -> mm_interconnect_0:HW2_timer_sw_agent_readdata
	wire         mm_interconnect_0_hw2_timer_sw_agent_waitrequest;      // HW2:timer_sw_agent_waitrequest -> mm_interconnect_0:HW2_timer_sw_agent_waitrequest
	wire   [5:0] mm_interconnect_0_hw2_timer_sw_agent_address;          // mm_interconnect_0:HW2_timer_sw_agent_address -> HW2:timer_sw_agent_address
	wire         mm_interconnect_0_hw2_timer_sw_agent_read;             // mm_interconnect_0:HW2_timer_sw_agent_read -> HW2:timer_sw_agent_read
	wire   [3:0] mm_interconnect_0_hw2_timer_sw_agent_byteenable;       // mm_interconnect_0:HW2_timer_sw_agent_byteenable -> HW2:timer_sw_agent_byteenable
	wire         mm_interconnect_0_hw2_timer_sw_agent_readdatavalid;    // HW2:timer_sw_agent_readdatavalid -> mm_interconnect_0:HW2_timer_sw_agent_readdatavalid
	wire         mm_interconnect_0_hw2_timer_sw_agent_write;            // mm_interconnect_0:HW2_timer_sw_agent_write -> HW2:timer_sw_agent_write
	wire  [31:0] mm_interconnect_0_hw2_timer_sw_agent_writedata;        // mm_interconnect_0:HW2_timer_sw_agent_writedata -> HW2:timer_sw_agent_writedata
	wire         irq_mapper_receiver0_irq;                              // DEBUG:av_irq -> irq_mapper:receiver0_irq
	wire  [15:0] hw2_platform_irq_rx_irq;                               // irq_mapper:sender_irq -> HW2:platform_irq_rx_irq
	wire         rst_controller_reset_out_reset;                        // rst_controller:reset_out -> [DEBUG:rst_n, HW2:reset_reset, KEYS:reset_n, LEDS:reset_n, SDRAM:reset, SWITCHES:reset_n, irq_mapper:reset, mm_interconnect_0:HW2_reset_reset_bridge_in_reset_reset, rst_translator:in_reset]
	wire         rst_controller_reset_out_reset_req;                    // rst_controller:reset_req -> [SDRAM:reset_req, rst_translator:reset_req_in]

	altera_avalon_jtag_uart #(
		.readBufferDepth            (64),
		.readIRQThreshold           (8),
		.useRegistersForReadBuffer  (0),
		.useRegistersForWriteBuffer (0),
		.writeBufferDepth           (64),
		.writeIRQThreshold          (8),
		.printingMethod             (0),
		.FIFO_WIDTH                 (8),
		.WR_WIDTHU                  (6),
		.RD_WIDTHU                  (6),
		.write_le                   ("ON"),
		.read_le                    ("ON"),
		.HEX_WRITE_DEPTH_STR        (64),
		.HEX_READ_DEPTH_STR         (64),
		.legacySignalAllow          (0)
	) debug (
		.clk            (clk_clk),                                               //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                       //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_debug_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_debug_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_debug_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_debug_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_debug_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_debug_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_debug_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver0_irq)                               //               irq.irq
	);

	HW2_HW2 hw2 (
		.clk                          (clk_clk),                                            //                 clk.clk
		.reset_reset                  (rst_controller_reset_out_reset),                     //               reset.reset
		.platform_irq_rx_irq          (hw2_platform_irq_rx_irq),                            //     platform_irq_rx.irq
		.ndm_reset_in_reset           (hw2_dbg_reset_out_reset),                            //        ndm_reset_in.reset
		.timer_sw_agent_address       (mm_interconnect_0_hw2_timer_sw_agent_address),       //      timer_sw_agent.address
		.timer_sw_agent_byteenable    (mm_interconnect_0_hw2_timer_sw_agent_byteenable),    //                    .byteenable
		.timer_sw_agent_read          (mm_interconnect_0_hw2_timer_sw_agent_read),          //                    .read
		.timer_sw_agent_readdata      (mm_interconnect_0_hw2_timer_sw_agent_readdata),      //                    .readdata
		.timer_sw_agent_write         (mm_interconnect_0_hw2_timer_sw_agent_write),         //                    .write
		.timer_sw_agent_writedata     (mm_interconnect_0_hw2_timer_sw_agent_writedata),     //                    .writedata
		.timer_sw_agent_waitrequest   (mm_interconnect_0_hw2_timer_sw_agent_waitrequest),   //                    .waitrequest
		.timer_sw_agent_readdatavalid (mm_interconnect_0_hw2_timer_sw_agent_readdatavalid), //                    .readdatavalid
		.instruction_manager_awaddr   (hw2_instruction_manager_awaddr),                     // instruction_manager.awaddr
		.instruction_manager_awprot   (hw2_instruction_manager_awprot),                     //                    .awprot
		.instruction_manager_awvalid  (hw2_instruction_manager_awvalid),                    //                    .awvalid
		.instruction_manager_awready  (hw2_instruction_manager_awready),                    //                    .awready
		.instruction_manager_wdata    (hw2_instruction_manager_wdata),                      //                    .wdata
		.instruction_manager_wstrb    (hw2_instruction_manager_wstrb),                      //                    .wstrb
		.instruction_manager_wvalid   (hw2_instruction_manager_wvalid),                     //                    .wvalid
		.instruction_manager_wready   (hw2_instruction_manager_wready),                     //                    .wready
		.instruction_manager_bresp    (hw2_instruction_manager_bresp),                      //                    .bresp
		.instruction_manager_bvalid   (hw2_instruction_manager_bvalid),                     //                    .bvalid
		.instruction_manager_bready   (hw2_instruction_manager_bready),                     //                    .bready
		.instruction_manager_araddr   (hw2_instruction_manager_araddr),                     //                    .araddr
		.instruction_manager_arprot   (hw2_instruction_manager_arprot),                     //                    .arprot
		.instruction_manager_arvalid  (hw2_instruction_manager_arvalid),                    //                    .arvalid
		.instruction_manager_arready  (hw2_instruction_manager_arready),                    //                    .arready
		.instruction_manager_rdata    (hw2_instruction_manager_rdata),                      //                    .rdata
		.instruction_manager_rresp    (hw2_instruction_manager_rresp),                      //                    .rresp
		.instruction_manager_rvalid   (hw2_instruction_manager_rvalid),                     //                    .rvalid
		.instruction_manager_rready   (hw2_instruction_manager_rready),                     //                    .rready
		.data_manager_awaddr          (hw2_data_manager_awaddr),                            //        data_manager.awaddr
		.data_manager_awprot          (hw2_data_manager_awprot),                            //                    .awprot
		.data_manager_awvalid         (hw2_data_manager_awvalid),                           //                    .awvalid
		.data_manager_awready         (hw2_data_manager_awready),                           //                    .awready
		.data_manager_wdata           (hw2_data_manager_wdata),                             //                    .wdata
		.data_manager_wstrb           (hw2_data_manager_wstrb),                             //                    .wstrb
		.data_manager_wvalid          (hw2_data_manager_wvalid),                            //                    .wvalid
		.data_manager_wready          (hw2_data_manager_wready),                            //                    .wready
		.data_manager_bresp           (hw2_data_manager_bresp),                             //                    .bresp
		.data_manager_bvalid          (hw2_data_manager_bvalid),                            //                    .bvalid
		.data_manager_bready          (hw2_data_manager_bready),                            //                    .bready
		.data_manager_araddr          (hw2_data_manager_araddr),                            //                    .araddr
		.data_manager_arprot          (hw2_data_manager_arprot),                            //                    .arprot
		.data_manager_arvalid         (hw2_data_manager_arvalid),                           //                    .arvalid
		.data_manager_arready         (hw2_data_manager_arready),                           //                    .arready
		.data_manager_rdata           (hw2_data_manager_rdata),                             //                    .rdata
		.data_manager_rresp           (hw2_data_manager_rresp),                             //                    .rresp
		.data_manager_rvalid          (hw2_data_manager_rvalid),                            //                    .rvalid
		.data_manager_rready          (hw2_data_manager_rready),                            //                    .rready
		.dm_agent_address             (mm_interconnect_0_hw2_dm_agent_address),             //            dm_agent.address
		.dm_agent_read                (mm_interconnect_0_hw2_dm_agent_read),                //                    .read
		.dm_agent_readdata            (mm_interconnect_0_hw2_dm_agent_readdata),            //                    .readdata
		.dm_agent_write               (mm_interconnect_0_hw2_dm_agent_write),               //                    .write
		.dm_agent_writedata           (mm_interconnect_0_hw2_dm_agent_writedata),           //                    .writedata
		.dm_agent_waitrequest         (mm_interconnect_0_hw2_dm_agent_waitrequest),         //                    .waitrequest
		.dm_agent_readdatavalid       (mm_interconnect_0_hw2_dm_agent_readdatavalid),       //                    .readdatavalid
		.dbg_reset_out_reset          (hw2_dbg_reset_out_reset)                             //       dbg_reset_out.reset
	);

	HW2_KEYS keys (
		.clk      (clk_clk),                            //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),    //               reset.reset_n
		.address  (mm_interconnect_0_keys_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_keys_s1_readdata), //                    .readdata
		.in_port  (keys_export)                         // external_connection.export
	);

	HW2_LEDS leds (
		.clk        (clk_clk),                              //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),      //               reset.reset_n
		.address    (mm_interconnect_0_leds_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_leds_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_leds_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_leds_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_leds_s1_readdata),   //                    .readdata
		.out_port   (leds_export)                           // external_connection.export
	);

	HW2_SDRAM sdram (
		.clk        (clk_clk),                               //   clk1.clk
		.address    (mm_interconnect_0_sdram_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_sdram_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_sdram_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_sdram_s1_write),      //       .write
		.readdata   (mm_interconnect_0_sdram_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_sdram_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_sdram_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),        // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req),    //       .reset_req
		.freeze     (1'b0)                                   // (terminated)
	);

	HW2_SWITCHES switches (
		.clk      (clk_clk),                                //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),        //               reset.reset_n
		.address  (mm_interconnect_0_switches_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_switches_s1_readdata), //                    .readdata
		.in_port  (switches_export)                         // external_connection.export
	);

	HW2_mm_interconnect_0 mm_interconnect_0 (
		.HW2_data_manager_awaddr               (hw2_data_manager_awaddr),                               //                HW2_data_manager.awaddr
		.HW2_data_manager_awprot               (hw2_data_manager_awprot),                               //                                .awprot
		.HW2_data_manager_awvalid              (hw2_data_manager_awvalid),                              //                                .awvalid
		.HW2_data_manager_awready              (hw2_data_manager_awready),                              //                                .awready
		.HW2_data_manager_wdata                (hw2_data_manager_wdata),                                //                                .wdata
		.HW2_data_manager_wstrb                (hw2_data_manager_wstrb),                                //                                .wstrb
		.HW2_data_manager_wvalid               (hw2_data_manager_wvalid),                               //                                .wvalid
		.HW2_data_manager_wready               (hw2_data_manager_wready),                               //                                .wready
		.HW2_data_manager_bresp                (hw2_data_manager_bresp),                                //                                .bresp
		.HW2_data_manager_bvalid               (hw2_data_manager_bvalid),                               //                                .bvalid
		.HW2_data_manager_bready               (hw2_data_manager_bready),                               //                                .bready
		.HW2_data_manager_araddr               (hw2_data_manager_araddr),                               //                                .araddr
		.HW2_data_manager_arprot               (hw2_data_manager_arprot),                               //                                .arprot
		.HW2_data_manager_arvalid              (hw2_data_manager_arvalid),                              //                                .arvalid
		.HW2_data_manager_arready              (hw2_data_manager_arready),                              //                                .arready
		.HW2_data_manager_rdata                (hw2_data_manager_rdata),                                //                                .rdata
		.HW2_data_manager_rresp                (hw2_data_manager_rresp),                                //                                .rresp
		.HW2_data_manager_rvalid               (hw2_data_manager_rvalid),                               //                                .rvalid
		.HW2_data_manager_rready               (hw2_data_manager_rready),                               //                                .rready
		.HW2_instruction_manager_awaddr        (hw2_instruction_manager_awaddr),                        //         HW2_instruction_manager.awaddr
		.HW2_instruction_manager_awprot        (hw2_instruction_manager_awprot),                        //                                .awprot
		.HW2_instruction_manager_awvalid       (hw2_instruction_manager_awvalid),                       //                                .awvalid
		.HW2_instruction_manager_awready       (hw2_instruction_manager_awready),                       //                                .awready
		.HW2_instruction_manager_wdata         (hw2_instruction_manager_wdata),                         //                                .wdata
		.HW2_instruction_manager_wstrb         (hw2_instruction_manager_wstrb),                         //                                .wstrb
		.HW2_instruction_manager_wvalid        (hw2_instruction_manager_wvalid),                        //                                .wvalid
		.HW2_instruction_manager_wready        (hw2_instruction_manager_wready),                        //                                .wready
		.HW2_instruction_manager_bresp         (hw2_instruction_manager_bresp),                         //                                .bresp
		.HW2_instruction_manager_bvalid        (hw2_instruction_manager_bvalid),                        //                                .bvalid
		.HW2_instruction_manager_bready        (hw2_instruction_manager_bready),                        //                                .bready
		.HW2_instruction_manager_araddr        (hw2_instruction_manager_araddr),                        //                                .araddr
		.HW2_instruction_manager_arprot        (hw2_instruction_manager_arprot),                        //                                .arprot
		.HW2_instruction_manager_arvalid       (hw2_instruction_manager_arvalid),                       //                                .arvalid
		.HW2_instruction_manager_arready       (hw2_instruction_manager_arready),                       //                                .arready
		.HW2_instruction_manager_rdata         (hw2_instruction_manager_rdata),                         //                                .rdata
		.HW2_instruction_manager_rresp         (hw2_instruction_manager_rresp),                         //                                .rresp
		.HW2_instruction_manager_rvalid        (hw2_instruction_manager_rvalid),                        //                                .rvalid
		.HW2_instruction_manager_rready        (hw2_instruction_manager_rready),                        //                                .rready
		.clk_0_clk_clk                         (clk_clk),                                               //                       clk_0_clk.clk
		.HW2_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                        // HW2_reset_reset_bridge_in_reset.reset
		.DEBUG_avalon_jtag_slave_address       (mm_interconnect_0_debug_avalon_jtag_slave_address),     //         DEBUG_avalon_jtag_slave.address
		.DEBUG_avalon_jtag_slave_write         (mm_interconnect_0_debug_avalon_jtag_slave_write),       //                                .write
		.DEBUG_avalon_jtag_slave_read          (mm_interconnect_0_debug_avalon_jtag_slave_read),        //                                .read
		.DEBUG_avalon_jtag_slave_readdata      (mm_interconnect_0_debug_avalon_jtag_slave_readdata),    //                                .readdata
		.DEBUG_avalon_jtag_slave_writedata     (mm_interconnect_0_debug_avalon_jtag_slave_writedata),   //                                .writedata
		.DEBUG_avalon_jtag_slave_waitrequest   (mm_interconnect_0_debug_avalon_jtag_slave_waitrequest), //                                .waitrequest
		.DEBUG_avalon_jtag_slave_chipselect    (mm_interconnect_0_debug_avalon_jtag_slave_chipselect),  //                                .chipselect
		.HW2_dm_agent_address                  (mm_interconnect_0_hw2_dm_agent_address),                //                    HW2_dm_agent.address
		.HW2_dm_agent_write                    (mm_interconnect_0_hw2_dm_agent_write),                  //                                .write
		.HW2_dm_agent_read                     (mm_interconnect_0_hw2_dm_agent_read),                   //                                .read
		.HW2_dm_agent_readdata                 (mm_interconnect_0_hw2_dm_agent_readdata),               //                                .readdata
		.HW2_dm_agent_writedata                (mm_interconnect_0_hw2_dm_agent_writedata),              //                                .writedata
		.HW2_dm_agent_readdatavalid            (mm_interconnect_0_hw2_dm_agent_readdatavalid),          //                                .readdatavalid
		.HW2_dm_agent_waitrequest              (mm_interconnect_0_hw2_dm_agent_waitrequest),            //                                .waitrequest
		.HW2_timer_sw_agent_address            (mm_interconnect_0_hw2_timer_sw_agent_address),          //              HW2_timer_sw_agent.address
		.HW2_timer_sw_agent_write              (mm_interconnect_0_hw2_timer_sw_agent_write),            //                                .write
		.HW2_timer_sw_agent_read               (mm_interconnect_0_hw2_timer_sw_agent_read),             //                                .read
		.HW2_timer_sw_agent_readdata           (mm_interconnect_0_hw2_timer_sw_agent_readdata),         //                                .readdata
		.HW2_timer_sw_agent_writedata          (mm_interconnect_0_hw2_timer_sw_agent_writedata),        //                                .writedata
		.HW2_timer_sw_agent_byteenable         (mm_interconnect_0_hw2_timer_sw_agent_byteenable),       //                                .byteenable
		.HW2_timer_sw_agent_readdatavalid      (mm_interconnect_0_hw2_timer_sw_agent_readdatavalid),    //                                .readdatavalid
		.HW2_timer_sw_agent_waitrequest        (mm_interconnect_0_hw2_timer_sw_agent_waitrequest),      //                                .waitrequest
		.KEYS_s1_address                       (mm_interconnect_0_keys_s1_address),                     //                         KEYS_s1.address
		.KEYS_s1_readdata                      (mm_interconnect_0_keys_s1_readdata),                    //                                .readdata
		.LEDS_s1_address                       (mm_interconnect_0_leds_s1_address),                     //                         LEDS_s1.address
		.LEDS_s1_write                         (mm_interconnect_0_leds_s1_write),                       //                                .write
		.LEDS_s1_readdata                      (mm_interconnect_0_leds_s1_readdata),                    //                                .readdata
		.LEDS_s1_writedata                     (mm_interconnect_0_leds_s1_writedata),                   //                                .writedata
		.LEDS_s1_chipselect                    (mm_interconnect_0_leds_s1_chipselect),                  //                                .chipselect
		.SDRAM_s1_address                      (mm_interconnect_0_sdram_s1_address),                    //                        SDRAM_s1.address
		.SDRAM_s1_write                        (mm_interconnect_0_sdram_s1_write),                      //                                .write
		.SDRAM_s1_readdata                     (mm_interconnect_0_sdram_s1_readdata),                   //                                .readdata
		.SDRAM_s1_writedata                    (mm_interconnect_0_sdram_s1_writedata),                  //                                .writedata
		.SDRAM_s1_byteenable                   (mm_interconnect_0_sdram_s1_byteenable),                 //                                .byteenable
		.SDRAM_s1_chipselect                   (mm_interconnect_0_sdram_s1_chipselect),                 //                                .chipselect
		.SDRAM_s1_clken                        (mm_interconnect_0_sdram_s1_clken),                      //                                .clken
		.SWITCHES_s1_address                   (mm_interconnect_0_switches_s1_address),                 //                     SWITCHES_s1.address
		.SWITCHES_s1_readdata                  (mm_interconnect_0_switches_s1_readdata)                 //                                .readdata
	);

	HW2_irq_mapper irq_mapper (
		.clk           (clk_clk),                        //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.sender_irq    (hw2_platform_irq_rx_irq)         //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (hw2_dbg_reset_out_reset),            // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
